services:
  postgres:
    image: postgres:16
    container_name: operador_financeiro_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - operador_financeiro_data:/var/lib/postgresql/data
    networks:
      - operador_financeiro_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  operador_financeiro_data:

networks:
  operador_financeiro_network:
    driver: bridge
